package com.vibame.telugupanchangamcalendar.helper;

public class Constant {
    public static final String MainBaseUrl = "https://admin.vibametelugucalendar.online/";
    //public static final String MainBaseUrl = "http://192.168.43.38/telugu_calendar/";
    public static final String BaseUrl = MainBaseUrl + "api/";
    public static final String PANCHANGAM_URL = BaseUrl + "panchangam.php";
    public static final String ALLDATALIST_URL = BaseUrl + "alldatalist.php";
    public static final String HOROSCOPE_URL = BaseUrl + "horoscope.php";

    public static final String ID = "id";
    public static final String PANCHANGAM_ID = "panchangam_id";
    public static final String MUHURTHAM_ID = "muhurtham_id";
    public static final String POOJALU_ID = "poojalu_id";
    public static final String GRAHALU_ID = "grahalu_id";
    public static final String SUBCATEGORY_ID = "subcategory_id";
    public static final String NAME = "name";
    public static final String IMAGE =  "image";
    public static final String PID = "pid";
    public static final String DATE = "date";
    public static final String TITLE = "title";
    public static final String SUCCESS = "success";
    public static final String MESSAGE = "message";
    public static final String DATA = "data";
    public static final String PANCHANGAM_LIST = "panchangam_list";
    public static final String PANCHANGAM_TAB_LIST = "panchangam_tab_list";
    public static final String FESTIVALS_LIST = "festivals_list";
    public static final String MUHURTHAM_LIST = "muhurtham_list";
    public static final String MUHURTHAM_TAB_LIST = "muhurtham_tab_list";
    public static final String POOJALU_LIST = "poojalu_list";
    public static final String POOJALU_SUB_MENU_LIST = "poojalu_sub_menu_list";
    public static final String POOJALU_TAB_LIST = "poojalu_tab_list";
    public static final String GRAHALU_LIST = "grahalu_list";
    public static final String GRAHALU_SUB_MENU_LIST = "grahalu_sub_menu_list";
    public static final String GRAHALU_TAB_LIST = "grahalu_tab_list";
    public static final String TAB = "tab";
    public static final String TYPE = "type";
    public static final String SUNRISE = "sunrise";
    public static final String SUNSET = "sunset";
    public static final String DESCRIPTION = "description";
    public static final String SUB_TITLE = "sub_title";
    public static final String SUB_DESCRIPTION = "sub_description";
    public static final String FESTIVAL = "festival";
    public static final String MOONRISE = "moonrise";

    public static final String MOONSET = "moonset";
    public static final String MUHURTHAM = "muhurtham";
    public static final String HOROSCOPE = "horoscope";
    public static final String RASI = "rasi";

    public static final String MESHAM = "Mesham";
    public static final String VRUSHABHAM = "Vrushabham";
    public static final String MIDHUNAM = "Midhunam";
    public static final String KARKATAKAM = "Karkatakam";
    public static final String SIMHAM = "Simham";
    public static final String KANYA = "Kanya";
    public static final String ThulaU = "Thula";
    public static final String VRUSCHIKAM = "Vruschikam";
    public static final String DHANUSSU = "Dhanussu";
    public static final String MAKARAM = "Makaram";
    public static final String KUMBHAM = "Kumbham";
    public static final String MEENAM = "Meenam";
    public static final String LUCKYNUMBER = "lucky_number";
    public static final String LUCKYCOLOR = "lucky_color";
    public static final String TREATMENT = "treatment";
    public static final String HEALTH = "health";
    public static final String WEALTH = "wealth";
    public static final String FAMILY = "family";
    public static final String THINGS_LOVE = "things_love";
    public static final String PROFESSION = "profession";
    public static final String MARRIED_LIFE = "married_life";
    public static final String YEARLY_HOROSCOPE_VARIANT = "yearly_horoscope_variant";
}